gems: [jekyll-paginate]
exclude: ['.idea','less','sources','CNAME','README.md','LICENSE','deploy.sh']
keep_files: ['.git','.idea']
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
timezone: Europe/Prague

markdown: kramdown
highlighter: rouge

name: Jindřich Doležy
author: Jindřich Doležy
email: jindrich@dolezy.cz
btc: 14ABuhZP7UnZQjwtyWrL19DUiof2jw5ykt
ga: UA-28722419-1
twitter: xDzindra

# url can not end with slash
url: https://dolezy.cz

defaults:
  -
    scope:
      path: ""
    values:
      lang: "cz"
      lang_url: ""
      layout: "default"
  -
    scope:
      path: "en"
    values:
      lang: "en"
      lang_url: "/en"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: ["blog"]
