exclude: ['.idea','less','sources','CNAME','README.md','LICENSE']
keep_files: ['.git','.idea']
permalink: pretty
paginate: 5
timezone: Europe/Prague

markdown: redcarpet
pygments: true

name: Jindřich Doležy
author: Jindřich Doležy
email: jindrich@dolezy.cz

# url and base path can not end with slash
url: http://blog.dolezy.cz
basePath:
