exclude: ['.idea','less','sources','CNAME','README.md','LICENSE']
keep_files: ['.git','.idea']
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
timezone: Europe/Prague

markdown: kramdown
highlighter: pygments

name: Jindřich Doležy
author: Jindřich Doležy
email: jindrich@dolezy.cz
btc: 14ABuhZP7UnZQjwtyWrL19DUiof2jw5ykt

# url and baseurl can not end with slash
url: http://blog.dolezy.cz
baseurl:

defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      lang_url: ""
      layout: "default"
  -
    scope:
      path: "cs"
    values:
      lang: "cs"
      lang_url: "/cs"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: ["blog"]
